
import type { Metadata } from 'next'
 
// These styles apply to every route in the application
import Navbar from './components/Navbar';
import { ThemeProviderWrapper } from './themes/ThemeContext';
import { Footer } from './components/Footer';
 
const navigation = [
  { name: "Home", href: "/", current: true },
  { name: "Paginas web", href: "/web-development", current: false },
  { name: "Apps moviles", href: "movile-development", current: false },
  { name: "Nosotros", href: "/about-us", current: false },
  { name: "Contactanos", href: "/contact", current: false },
];

export const metadata: Metadata = {
  title: 'ApexLogic',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <ThemeProviderWrapper>
      <Navbar navigation={navigation}/>
        {children}
        <Footer/>
      </ThemeProviderWrapper>
        </body>
    </html>
  )
}